### ISSUE TITLE
How to run on different port

### ISSUE THREAD

**Issue by crebuh** [pottava/docker-webui#6]
Hey, first of all thanks for this great exentsion to docker!

Currently I'm trying to run the application with the following command:

> docker run -p 9000:9000 --rm -v /var/run/docker.sock:/var/run/docker.sock pottava/docker-webui

My problem is that on my server I'm using nginx as a reverse proxy to link request from port 80 to an internal port. I'm also using redis, which I'm running on port 9000. So i have to change the port for the docker-webui to something different, because I cannot change the redis port.

I tried it with 

> docker run -p 9001:9001 --rm -v /var/run/docker.sock:/var/run/docker.sock pottava/docker-webui

but the app is still listening on port 9000. Any idea on how to configure this?

**Comment by pottava** [comment]
@crebuh Thank you for using this application. You can change the port with the `APP_PORT` environment variable. Something like the following:

`docker run -p 9001:9001 -e APP_PORT=9001 --rm -v /var/run/docker.sock:/var/run/docker.sock pottava/docker-webui`

**Comment by crebuh** [comment]
@pottava 

thanks this worked :+1:

**Comment by crebuh** [comment]
@pottava 

trying to include your image into my docker-compose file but I dont know where it is failing here are my docker-compose files

docker-compose.yml

``
  docker_webui:
    image: pottava/docker-webui
    ports:
      - 9001:9001
    volumes:
      - "${BASE_MOUNT_PATH}:/etc/docker-compose/cert"
    environment:
      - DOCKER_HOST
      - DOCKER_CERT_PATH=/etc/docker-compose/cert
      - APP_LABEL_OVERRIDE_NAMES=com.docker.compose.service
      - APP_LABEL_FILTERS=com.docker.compose.service
``

docker-compose.dev.yml (have 3 files for different environments)

``
  docker_webui:
    restart: always
    image: pottava/docker-webui
``

The images are built but when I try to open it in the browser, I get an 502 Bad Gateway error, I guess the APP_PORT variable should also be set to 9001 .. but how?

**Comment by pottava** [comment]
Hi @crebuh,

You can change the port with following definitions! Let me know if it does not work :)

```
docker_webui:
  image: pottava/docker-webui
  ports:
    - "9001:9001"
  volumes:
    - "${BASE_MOUNT_PATH}:/etc/docker-compose/cert"
  environment:
    - APP_PORT=9001
    - DOCKER_HOST
    - DOCKER_CERT_PATH=/etc/docker-compose/cert
    - APP_LABEL_OVERRIDE_NAMES=com.docker.compose.service
    - APP_LABEL_FILTERS=com.docker.compose.service
```

**Comment by crebuh** [comment]
@pottava 

at least it is not throwing an error when I compose, but nginx is saying bad gateway ... when I check with docker ps everything seems to be fine

> bf9276426197  pottava/docker-webui  "docker-webui" 33 minutes ago      Up 33 minutes   9000/tcp, 0.0.0.0:9001->9001/tcp  docker_webui_1

the funny thing is when I just run it with 

> docker run -p 9001:9001 -e APP_PORT=9001 --rm -v /var/run/docker.sock:/var/run/docker.sock pottava/docker-webui

it is working with the same nginx settings

**edit**

got it running know, I had to add it to my docker-network, by adding 

    networks:
      - my_network

but now it is not recognizing the other containers so nothing is shown in the UI. I guess I have to modify the variables for the DOCKER_HOST and/or DOCKER_CERT_PATH?

**Comment by pottava** [comment]
@crebuh 

Yes, I think. Can you try the following configurations?

```
docker_webui:
  image: pottava/docker-webui
  ports:
    - "9001:9001"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - APP_PORT=9001
    - APP_LABEL_OVERRIDE_NAMES=com.docker.compose.service
    - APP_LABEL_FILTERS=com.docker.compose.service
```
